export default [
  { char: "🎮", label: "Video game", category: "activities" },
  { char: "🕹️", label: "Joystick", category: "activities" },
  { char: "🎰", label: "Slot machine", category: "activities" },
  { char: "🎲", label: "Game die", category: "activities" },
  { char: "🧩", label: "Puzzle piece", category: "activities" },
  { char: "🧸", label: "Teddy bear", category: "activities" },
  { char: "♠️", label: "Spade suit", category: "activities" },
  { char: "♥️", label: "Heart suit", category: "activities" },
  { char: "♦️", label: "Diamond suit", category: "activities" },
  { char: "♣️", label: "Club suit", category: "activities" },
  { char: "♟️", label: "Chess pawn", category: "activities" },
  { char: "🎭", label: "Theater arts", category: "activities" },
  { char: "🎨", label: "Artist palette", category: "activities" },
  { char: "🧵", label: "Thread", category: "activities" },
  { char: "🧶", label: "Yarn", category: "activities" },
  { char: "🎺", label: "Trumpet", category: "activities" },
  { char: "🎻", label: "Violin", category: "activities" },
  { char: "🎹", label: "Musical keyboard", category: "activities" },
  { char: "🎸", label: "Guitar", category: "activities" },
  { char: "🎷", label: "Saxophone", category: "activities" },
  { char: "🥁", label: "Drum", category: "activities" },
  { char: "🎧", label: "Headphone", category: "activities" },
  { char: "🎤", label: "Microphone", category: "activities" }
];
