/**
 * Signal Share Emoji Pack
 * A comprehensive list of emojis for the Direct Messenger.
 */

export const EMOJI_CATEGORIES = [
  { id: "faces", label: "Faces", icon: "😀" },
  { id: "gestures", label: "Gestures", icon: "👍" },
  { id: "food", label: "Food", icon: "🍕" },
  { id: "nature", label: "Nature", icon: "🌿" },
  { id: "places", label: "Places", icon: "🚀" },
  { id: "activities", label: "Activities", icon: "🏀" },
  { id: "objects", label: "Objects", icon: "🎉" }
];

export const EMOJI_PACK = [
  // Faces (Faces & Emotion)
  { char: "😀", label: "Grinning face", category: "faces", tags: "happy joy smile" },
  { char: "😂", label: "Tears of joy", category: "faces", tags: "laugh lol happy joy" },
  { char: "😍", label: "Heart eyes", category: "faces", tags: "love adore like heart" },
  { char: "🥰", label: "Smiling face with hearts", category: "faces", tags: "love affection crush" },
  { char: "😎", label: "Smiling face with sunglasses", category: "faces", tags: "cool chill sun" },
  { char: "🥳", label: "Partying face", category: "faces", tags: "party celebration birthday" },
  { char: "🤩", label: "Star-struck", category: "faces", tags: "star wow amazed" },
  { char: "😊", label: "Smiling face with smiling eyes", category: "faces", tags: "happy shy smile" },
  { char: "😇", label: "Smiling face with halo", category: "faces", tags: "angel good innocent" },
  { char: "🤔", label: "Thinking face", category: "faces", tags: "think puzzle question" },
  { char: "🤨", label: "Face with raised eyebrow", category: "faces", tags: "skeptical doubt hmmm" },
  { char: "🤫", label: "Shushing face", category: "faces", tags: "quiet silence secret" },
  { char: "🤤", label: "Drooling face", category: "faces", tags: "hungry delicious want" },
  { char: "😴", label: "Sleeping face", category: "faces", tags: "sleep tired zzz" },
  { char: "🤢", label: "Nauseated face", category: "faces", tags: "sick gross vomit" },
  { char: "🤯", label: "Exploding head", category: "faces", tags: "mind blown shock wow" },
  { char: "😭", label: "Loudly crying face", category: "faces", tags: "sad cry upset" },
  { char: "😤", label: "Face with steam from nose", category: "faces" },
  { char: "😡", label: "Pouting face", category: "faces" },
  { char: "🥺", label: "Pleading face", category: "faces" },
  { char: "✨", label: "Sparkles", category: "faces" },
  { char: "🔥", label: "Fire", category: "faces" },
  { char: "💯", label: "One hundred", category: "faces" },
  { char: "❤️", label: "Red heart", category: "faces" },
  { char: "🧡", label: "Orange heart", category: "faces" },
  { char: "💛", label: "Yellow heart", category: "faces" },
  { char: "💚", label: "Green heart", category: "faces" },
  { char: "💙", label: "Blue heart", category: "faces" },
  { char: "💜", label: "Purple heart", category: "faces" },
  { char: "🖤", label: "Black heart", category: "faces" },
  { char: "🤍", label: "White heart", category: "faces" },
  { char: "🤎", label: "Brown heart", category: "faces" },
  { char: "💔", label: "Broken heart", category: "faces" },
  { char: "❣️", label: "Heart exclamation", category: "faces" },
  { char: "💕", label: "Two hearts", category: "faces" },
  { char: "🤪", label: "Zany face", category: "faces" },
  { char: "🫠", label: "Melting face", category: "faces" },
  { char: "🫡", label: "Saluting face", category: "faces" },
  { char: "🫢", label: "Face with open eyes and hand over mouth", category: "faces" },
  { char: "🫣", label: "Face with peeking eye", category: "faces" },
  { char: "🥱", label: "Yawning face", category: "faces" },
  { char: "🤡", label: "Clown face", category: "faces" },
  { char: "💀", label: "Skull", category: "faces" },
  { char: "👽", label: "Alien", category: "faces" },
  { char: "👾", label: "Alien monster", category: "faces" },
  { char: "🤖", label: "Robot", category: "faces" },
  { char: "🎃", label: "Jack-o-lantern", category: "faces" },
  { char: "👻", label: "Ghost", category: "faces" },
  { char: "💩", label: "Pile of poo", category: "faces" },
  { char: "👿", label: "Angry face with horns", category: "faces" },
  { char: "👹", label: "Ogre", category: "faces" },
  { char: "👺", label: "Goblin", category: "faces" },
  { char: "👾", label: "Alien monster", category: "faces" },
  { char: "🤖", label: "Robot", category: "faces" },
  { char: "😺", label: "Grinning cat", category: "faces" },
  { char: "😸", label: "Grinning cat with smiling eyes", category: "faces" },
  { char: "😻", label: "Smiling cat with heart-eyes", category: "faces" },
  { char: "😽", label: "Kissing cat", category: "faces" },
  { char: "🙀", label: "Weary cat", category: "faces" },
  { char: "😿", label: "Crying cat", category: "faces" },
  { char: "😾", label: "Pouting cat", category: "faces" },
  { char: "🙈", label: "See-no-evil monkey", category: "faces" },
  { char: "🙉", label: "Hear-no-evil monkey", category: "faces" },
  { char: "🙊", label: "Speak-no-evil monkey", category: "faces" },
  { char: "💋", label: "Kiss mark", category: "faces" },
  { char: "💌", label: "Love letter", category: "faces" },
  { char: "💘", label: "Heart with arrow", category: "faces" },
  { char: "💝", label: "Heart with ribbon", category: "faces" },
  { char: "💖", label: "Sparkling heart", category: "faces" },
  { char: "💗", label: "Growing heart", category: "faces" },
  { char: "💓", label: "Beating heart", category: "faces" },
  { char: "💞", label: "Revolving hearts", category: "faces" },
  { char: "💟", label: "Heart decoration", category: "faces" },
  { char: "💢", label: "Anger symbol", category: "faces" },
  { char: "💥", label: "Collision", category: "faces" },
  { char: "💫", label: "Dizzy", category: "faces" },
  { char: "💦", label: "Sweat droplets", category: "faces" },
  { char: "💨", label: "Dash", category: "faces" },
  { char: "💬", label: "Speech balloon", category: "faces" },
  { char: "💭", label: "Thought balloon", category: "faces" },
  { char: "💤", label: "Zzz", category: "faces" },

  // Gestures (Gestures & Body)
  { char: "👍", label: "Thumbs up", category: "gestures", tags: "yes good okay like" },
  { char: "👎", label: "Thumbs down", category: "gestures", tags: "no bad dislike" },
  { char: "👌", label: "OK hand", category: "gestures", tags: "ok okay good" },
  { char: "✌️", label: "Victory hand", category: "gestures", tags: "peace victory two" },
  { char: "🤞", label: "Crossed fingers", category: "gestures", tags: "luck hope" },
  { char: "🤟", label: "Love-you gesture", category: "gestures" },
  { char: "🤘", label: "Sign of the horns", category: "gestures", tags: "rock metal music" },
  { char: "🤙", label: "Call me hand", category: "gestures", tags: "call phone shaka" },
  { char: "👊", label: "Oncoming fist", category: "gestures" },
  { char: "👏", label: "Clapping hands", category: "gestures", tags: "clap bravo well done" },
  { char: "🙌", label: "Raising hands", category: "gestures", tags: "praise celebrate joy" },
  { char: "👐", label: "Open hands", category: "gestures" },
  { char: "🤲", label: "Palms up together", category: "gestures" },
  { char: "🙏", label: "Folded hands", category: "gestures", tags: "pray please thanks" },
  { char: "🤝", label: "Handshake", category: "gestures", tags: "deal agree meet" },
  { char: "💪", label: "Flexed biceps", category: "gestures", tags: "strong muscle power" },
  { char: "🦾", label: "Mechanical arm", category: "gestures" },
  { char: "🧠", label: "Brain", category: "gestures", tags: "brain smart think" },
  { char: "👀", label: "Eyes", category: "gestures" },
  { char: "🖕", label: "Middle finger", category: "gestures" },
  { char: "💅", label: "Nail polish", category: "gestures" },
  { char: "🤳", label: "Selfie", category: "gestures" },
  { char: "🦶", label: "Foot", category: "gestures" },
  { char: "🦵", label: "Leg", category: "gestures" },
  { char: "🦿", label: "Mechanical leg", category: "gestures" },
  { char: "✍️", label: "Writing hand", category: "gestures" },
  { char: "🫂", label: "People hugging", category: "gestures" },
  { char: "👂", label: "Ear", category: "gestures" },
  { char: "👃", label: "Nose", category: "gestures" },
  { char: "👅", label: "Tongue", category: "gestures" },
  { char: "👄", label: "Mouth", category: "gestures" },

  // Objects (Objects & Symbols)
  { char: "🎉", label: "Party popper", category: "objects" },
  { char: "🎊", label: "Confetti ball", category: "objects" },
  { char: "🎈", label: "Balloon", category: "objects" },
  { char: "🎁", label: "Wrapped gift", category: "objects" },
  { char: "💎", label: "Gem stone", category: "objects" },
  { char: "💡", label: "Light bulb", category: "objects" },
  { char: "🔋", label: "Battery", category: "objects" },
  { char: "💻", label: "Laptop", category: "objects" },
  { char: "📱", label: "Mobile phone", category: "objects" },
  { char: "🚀", label: "Rocket", category: "objects" },
  { char: "🛸", label: "Flying saucer", category: "objects" },
  { char: "🌈", label: "Rainbow", category: "objects" },
  { char: "🌊", label: "Water wave", category: "objects" },
  { char: "🌍", label: "Earth globe Europe-Africa", category: "objects" },
  { char: "🍕", label: "Pizza", category: "objects" },
  { char: "🍔", label: "Hamburger", category: "objects" },
  { char: "🍟", label: "French fries", category: "objects" },
  { char: "☕", label: "Hot beverage", category: "objects" },
  { char: "🍺", label: "Beer mug", category: "objects" },
  { char: "🍷", label: "Wine glass", category: "objects" },
  { char: "🍹", label: "Tropical drink", category: "objects" },
  { char: "🍦", label: "Soft ice cream", category: "objects" },
  { char: "🍩", label: "Doughnut", category: "objects" },
  { char: "🍪", label: "Cookie", category: "objects" },
  { char: "🍫", label: "Chocolate bar", category: "objects" },
  { char: "🎨", label: "Artist palette", category: "objects" },
  { char: "🎤", label: "Microphone", category: "objects" },
  { char: "🎧", label: "Headphone", category: "objects" },
  { char: "🎹", label: "Musical keyboard", category: "objects" },
  { char: "🎸", label: "Guitar", category: "objects" },
  { char: "🎻", label: "Violin", category: "objects" },
  { char: "🎺", label: "Trumpet", category: "objects" },
  { char: "🎷", label: "Saxophone", category: "objects" },
  { char: "🥁", label: "Drum", category: "objects" },
  { char: "🎮", label: "Video game", category: "objects" },
  { char: "🎲", label: "Game die", category: "objects" },
  { char: "🎰", label: "Slot machine", category: "objects" },
  { char: "♟️", label: "Chess pawn", category: "objects" },
  { char: "🎭", label: "Theater arts", category: "objects" },
  { char: "🎬", label: "Clapper board", category: "objects" },
  { char: "📺", label: "Television", category: "objects" },
  { char: "📷", label: "Camera", category: "objects" },
  { char: "🕯️", label: "Candle", category: "objects" },
  { char: "🧨", label: "Firecracker", category: "objects" },
  { char: "🧧", label: "Red envelope", category: "objects" },
  { char: "🧿", label: "Nazar amulet", category: "objects" },
  
  // Nature
  { char: "🌿", label: "Herb", category: "nature" },
  { char: "🌵", label: "Cactus", category: "nature" },
  { char: "🌴", label: "Palm tree", category: "nature" },
  { char: "🌲", label: "Evergreen tree", category: "nature" },
  { char: "🌳", label: "Deciduous tree", category: "nature" },
  { char: "☘️", label: "Shamrock", category: "nature" },
  { char: "🍀", label: "Four leaf clover", category: "nature" },
  { char: "🍁", label: "Maple leaf", category: "nature" },
  { char: "🍂", label: "Fallen leaf", category: "nature" },
  { char: "🍄", label: "Mushroom", category: "nature" },
  { char: "🌹", label: "Rose", category: "nature" },
  { char: "🌺", label: "Hibiscus", category: "nature" },
  { char: "🌻", label: "Sunflower", category: "nature" },
  { char: "🌼", label: "Blossom", category: "nature" },
  { char: "🌷", label: "Tulip", category: "nature" },
  { char: "🪐", label: "Ringed planet", category: "nature" },
  { char: "🌙", label: "Crescent moon", category: "nature" },
  { char: "⭐", label: "Star", category: "nature" },
  { char: "☀️", label: "Sun", category: "nature" },
  { char: "☁️", label: "Cloud", category: "nature" },
  { char: "❄️", label: "Snowflake", category: "nature" },
  { char: "⚡", label: "Voltage", category: "nature" },
  { char: "🔥", label: "Fire", category: "nature" },
  
  // Activities
  { char: "🏀", label: "Basketball", category: "activities" },
  { char: "⚽", label: "Soccer ball", category: "activities" },
  { char: "🏈", label: "American football", category: "activities" },
  { char: "⚾", label: "Baseball", category: "activities" },
  { char: "🎾", label: "Tennis", category: "activities" },
  { char: "🏐", label: "Volleyball", category: "activities" },
  { char: "🏉", label: "Rugby football", category: "activities" },
  { char: "🎱", label: "Pool 8 ball", category: "activities" },
  { char: "🏓", label: "Ping pong", category: "activities" },
  { char: "🏸", label: "Badminton", category: "activities" },
  { char: "🥊", label: "Boxing glove", category: "activities" },
  { char: "🥋", label: "Martial arts uniform", category: "activities" },
  { char: "⛳", label: "Flag in hole", category: "activities" },
  { char: "🎣", label: "Fishing pole", category: "activities" },
  { char: "🏹", label: "Bow and arrow", category: "activities" },
  { char: "🛹", label: "Skateboard", category: "activities" },
  { char: "🚲", label: "Bicycle", category: "activities" },
  { char: "🏎️", label: "Racing car", category: "activities" },
  { char: "🏍️", label: "Motorcycle", category: "activities" },
  { char: "🏅", label: "Sports medal", category: "activities" },
  { char: "🏆", label: "Trophy", category: "activities" },
  { char: "🎬", label: "Clapper board", category: "activities" },
  { char: "🎮", label: "Video game", category: "activities" },
  { char: "🕹️", label: "Joystick", category: "activities" },
  { char: "🎰", label: "Slot machine", category: "activities" },
  { char: "🎲", label: "Game die", category: "activities" },
  { char: "🧩", label: "Puzzle piece", category: "activities" },
  { char: "🧸", label: "Teddy bear", category: "activities" },
  { char: "♠️", label: "Spade suit", category: "activities" },
  { char: "♥️", label: "Heart suit", category: "activities" },
  { char: "♦️", label: "Diamond suit", category: "activities" },
  { char: "♣️", label: "Club suit", category: "activities" },
  { char: "♟️", label: "Chess pawn", category: "activities" },
  { char: "🎭", label: "Theater arts", category: "activities" },
  { char: "🎨", label: "Artist palette", category: "activities" },
  { char: "🧵", label: "Thread", category: "activities" },
  { char: "🧶", label: "Yarn", category: "activities" },
  { char: "🎺", label: "Trumpet", category: "activities" },
  { char: "🎻", label: "Violin", category: "activities" },
  { char: "🎹", label: "Musical keyboard", category: "activities" },
  { char: "🎸", label: "Guitar", category: "activities" },
  { char: "🎷", label: "Saxophone", category: "activities" },
  { char: "🥁", label: "Drum", category: "activities" },
  { char: "🎧", label: "Headphone", category: "activities" },
  { char: "🎤", label: "Microphone", category: "activities" },

  // Food
  { char: "🍇", label: "Grapes", category: "food" },
  { char: "🍈", label: "Melon", category: "food" },
  { char: "🍉", label: "Watermelon", category: "food" },
  { char: "🍊", label: "Tangerine", category: "food" },
  { char: "🍋", label: "Lemon", category: "food" },
  { char: "🍌", label: "Banana", category: "food" },
  { char: "🍍", label: "Pineapple", category: "food" },
  { char: "🥭", label: "Mango", category: "food" },
  { char: "🍎", label: "Red apple", category: "food" },
  { char: "🍏", label: "Green apple", category: "food" },
  { char: "🍐", label: "Pear", category: "food" },
  { char: "🍑", label: "Peach", category: "food" },
  { char: "🍒", label: "Cherries", category: "food" },
  { char: "🍓", label: "Strawberry", category: "food" },
  { char: "🥝", label: "Kiwi fruit", category: "food" },
  { char: "🍅", label: "Tomato", category: "food" },
  { char: "🥥", label: "Coconut", category: "food" },
  { char: "🥑", label: "Avocado", category: "food" },
  { char: "🍆", label: "Eggplant", category: "food" },
  { char: "🥔", label: "Potato", category: "food" },
  { char: "🥕", label: "Carrot", category: "food" },
  { char: "🌽", label: "Ear of corn", category: "food" },
  { char: "🌶️", label: "Hot pepper", category: "food" },
  { char: "🥒", label: "Cucumber", category: "food" },
  { char: "🥬", label: "Leafy green", category: "food" },
  { char: "🥦", label: "Broccoli", category: "food" },
  { char: "🧄", label: "Garlic", category: "food" },
  { char: "🧅", label: "Onion", category: "food" },
  { char: "🍄", label: "Mushroom", category: "food" },
  { char: "🥜", label: "Peanuts", category: "food" },
  { char: "🌰", label: "Chestnut", category: "food" },
  { char: "🍞", label: "Bread", category: "food" },
  { char: "🥐", label: "Croissant", category: "food" },
  { char: "🥖", label: "Baguette bread", category: "food" },
  { char: "🥨", label: "Pretzel", category: "food" },
  { char: "🥯", label: "Bagel", category: "food" },
  { char: "🥞", label: "Pancakes", category: "food" },
  { char: "🧇", label: "Waffle", category: "food" },
  { char: "🧀", label: "Cheese wedge", category: "food" },
  { char: "🍖", label: "Meat on bone", category: "food" },
  { char: "🍗", label: "Poultry leg", category: "food" },
  { char: "🥩", label: "Cut of meat", category: "food" },
  { char: "🥓", label: "Bacon", category: "food" },
  { char: "🍔", label: "Hamburger", category: "food" },
  { char: "🍟", label: "French fries", category: "food" },
  { char: "🍕", label: "Pizza", category: "food" },
  { char: "🌭", label: "Hot dog", category: "food" },
  { char: "🥪", label: "Sandwich", category: "food" },
  { char: "🌮", label: "Taco", category: "food" },
  { char: "🌯", label: "Burrito", category: "food" },
  { char: "🥙", label: "Stuffed flatbread", category: "food" },
  { char: "🧆", label: "Falafel", category: "food" },
  { char: "🍳", label: "Cooking", category: "food" },
  { char: "🥘", label: "Shallow pan of food", category: "food" },
  { char: "🍲", label: "Pot of food", category: "food" },
  { char: "🥣", label: "Bowl with spoon", category: "food" },
  { char: "🥗", label: "Green salad", category: "food" },
  { char: "🍿", label: "Popcorn", category: "food" },
  { char: "🧈", label: "Butter", category: "food" },
  { char: "🧂", label: "Salt", category: "food" },
  { char: "🥫", label: "Canned food", category: "food" },
  { char: "🍱", label: "Bento box", category: "food" },
  { char: "🍘", label: "Rice cracker", category: "food" },
  { char: "🍙", label: "Rice ball", category: "food" },
  { char: "🍚", label: "Cooked rice", category: "food" },
  { char: "🍛", label: "Curry rice", category: "food" },
  { char: "🍜", label: "Steaming bowl", category: "food" },
  { char: "🍝", label: "Spaghetti", category: "food" },
  { char: "🍠", label: "Roasted sweet potato", category: "food" },
  { char: "🍢", label: "Oden", category: "food" },
  { char: "🍣", label: "Sushi", category: "food" },
  { char: "🍤", label: "Fried shrimp", category: "food" },
  { char: "🍥", label: "Fish cake with swirl", category: "food" },
  { char: "🥮", label: "Moon cake", category: "food" },
  { char: "🍡", label: "Dango", category: "food" },
  { char: "🥟", label: "Dumpling", category: "food" },
  { char: "🥠", label: "Fortune cookie", category: "food" },
  { char: "🥡", label: "Takeout box", category: "food" },
  { char: "🍦", label: "Soft ice cream", category: "food" },
  { char: "🍧", label: "Shaved ice", category: "food" },
  { char: "🍨", label: "Ice cream", category: "food" },
  { char: "🍩", label: "Doughnut", category: "food" },
  { char: "🍪", label: "Cookie", category: "food" },
  { char: "🎂", label: "Birthday cake", category: "food" },
  { char: "🍰", label: "Shortcake", category: "food" },
  { char: "🧁", label: "Cupcake", category: "food" },
  { char: "🥧", label: "Pie", category: "food" },
  { char: "🍫", label: "Chocolate bar", category: "food" },
  { char: "🍬", label: "Candy", category: "food" },
  { char: "🍭", label: "Lollipop", category: "food" },
  { char: "🍮", label: "Custard", category: "food" },
  { char: "🍯", label: "Honey pot", category: "food" },
  { char: "🍼", label: "Baby bottle", category: "food" },
  { char: "🥛", label: "Glass of milk", category: "food" },
  { char: "☕", label: "Hot beverage", category: "food" },
  { char: "🍵", label: "Teacup without handle", category: "food" },
  { char: "🍶", label: "Sake", category: "food" },
  { char: "🍾", label: "Bottle with popping cork", category: "food" },
  { char: "🍷", label: "Wine glass", category: "food" },
  { char: "🍸", label: "Cocktail glass", category: "food" },
  { char: "🍹", label: "Tropical drink", category: "food" },
  { char: "🍺", label: "Beer mug", category: "food" },
  { char: "🍻", label: "Clinking beer mugs", category: "food" },
  { char: "🥂", label: "Clinking glasses", category: "food" },
  { char: "🥃", label: "Tumbler glass", category: "food" },
  { char: "🥤", label: "Cup with straw", category: "food" },
  { char: "🧃", label: "Beverage box", category: "food" },
  { char: "🧉", label: "Mate", category: "food" },
  { char: "🧊", label: "Ice", category: "food" },
  { char: "🥢", label: "Chopsticks", category: "food" },
  { char: "🍽️", label: "Fork and knife with plate", category: "food" },
  { char: "🍴", label: "Fork and knife", category: "food" },
  { char: "🥄", label: "Spoon", category: "food" },

  // Places
  { char: "🌍", label: "Earth globe Europe-Africa", category: "places" },
  { char: "🌎", label: "Earth globe Americas", category: "places" },
  { char: "🌏", label: "Earth globe Asia-Australia", category: "places" },
  { char: "🌐", label: "Globe with meridians", category: "places" },
  { char: "🗺️", label: "World map", category: "places" },
  { char: "🗾", label: "Map of Japan", category: "places" },
  { char: "🧭", label: "Compass", category: "places" },
  { char: "🏔️", label: "Snow-capped mountain", category: "places" },
  { char: "⛰️", label: "Mountain", category: "places" },
  { char: "🌋", label: "Volcano", category: "places" },
  { char: "🗻", label: "Mount Fuji", category: "places" },
  { char: "🏕️", label: "Camping", category: "places" },
  { char: "🏖️", label: "Beach with umbrella", category: "places" },
  { char: "🏜️", label: "Desert", category: "places" },
  { char: "🏝️", label: "Desert island", category: "places" },
  { char: "🏝️", label: "National park", category: "places" },
  { char: "🏞️", label: "Stadium", category: "places" },
  { char: "🏟️", label: "Classical building", category: "places" },
  { char: "🏛️", label: "Building construction", category: "places" },
  { char: "🏗️", label: "Brick", category: "places" },
  { char: "🧱", label: "Houses", category: "places" },
  { char: "🏘️", label: "Derelict house", category: "places" },
  { char: "🏚️", label: "House", category: "places" },
  { char: "🏠", label: "House with garden", category: "places" },
  { char: "🏡", label: "Office building", category: "places" },
  { char: "🏢", label: "Japanese post office", category: "places" },
  { char: "🏣", label: "Post office", category: "places" },
  { char: "🏤", label: "Hospital", category: "places" },
  { char: "🏥", label: "Bank", category: "places" },
  { char: "🏦", label: "Hotel", category: "places" },
  { char: "🏨", label: "Love hotel", category: "places" },
  { char: "🏩", label: "Convenience store", category: "places" },
  { char: "🏪", label: "School", category: "places" },
  { char: "🏫", label: "Department store", category: "places" },
  { char: "🏬", label: "Factory", category: "places" },
  { char: "🏭", label: "Japanese castle", category: "places" },
  { char: "🏯", label: "Castle", category: "places" },
  { char: "🏰", label: "Wedding", category: "places" },
  { char: "💒", label: "Tokyo tower", category: "places" },
  { char: "🗼", label: "Statue of Liberty", category: "places" },
  { char: "🗽", label: "Church", category: "places" },
  { char: "⛪", label: "Mosque", category: "places" },
  { char: "🕌", label: "Hindu temple", category: "places" },
  { char: "🛕", label: "Synagogue", category: "places" },
  { char: "🕍", label: "Shinto shrine", category: "places" },
  { char: "⛩️", label: "Kaaba", category: "places" },
  { char: "🕋", label: "Fountain", category: "places" },
  { char: "⛲", label: "Tent", category: "places" },
  { char: "⛺", label: "Foggy", category: "places" },
  { char: "🌁", label: "Night with stars", category: "places" },
  { char: "🌃", label: "Cityscape", category: "places" },
  { char: "🏙️", label: "Sunrise over mountains", category: "places" },
  { char: "🌄", label: "Sunrise", category: "places" },
  { char: "🌅", label: "Cityscape at dusk", category: "places" },
  { char: "🌆", label: "Sunset", category: "places" },
  { char: "🌇", label: "Bridge at night", category: "places" },
  { char: "🌉", label: "Hot springs", category: "places" },
  { char: "♨️", label: "Carousel horse", category: "places" },
  { char: "🎠", label: "Ferris wheel", category: "places" },
  { char: "🎡", label: "Roller coaster", category: "places" },
  { char: "🎢", label: "Barber pole", category: "places" },
  { char: "💈", label: "Circus tent", category: "places" },
  { char: "🎪", label: "Locomotive", category: "places" },
  { char: "🚂", label: "Railway car", category: "places" },
  { char: "🚃", label: "High-speed train", category: "places" },
  { char: "🚄", label: "Bullet train", category: "places" },
  { char: "🚅", label: "Train", category: "places" },
  { char: "🚆", label: "Metro", category: "places" },
  { char: "🚇", label: "Light rail", category: "places" },
  { char: "🚈", label: "Station", category: "places" },
  { char: "🚉", label: "Tram", category: "places" },
  { char: "🚊", label: "Monorail", category: "places" },
  { char: "🚝", label: "Mountain railway", category: "places" },
  { char: "🚞", label: "Tram car", category: "places" },
  { char: "🚋", label: "Bus", category: "places" },
  { char: "🚌", label: "Oncoming bus", category: "places" },
  { char: "🚍", label: "Trolleybus", category: "places" },
  { char: "🚎", label: "Minibus", category: "places" },
  { char: "🚐", label: "Ambulance", category: "places" },
  { char: "🚑", label: "Fire engine", category: "places" },
  { char: "🚒", label: "Police car", category: "places" },
  { char: "🚓", label: "Oncoming police car", category: "places" },
  { char: "🚔", label: "Taxi", category: "places" },
  { char: "🚕", label: "Oncoming taxi", category: "places" },
  { char: "🚖", label: "Automobile", category: "places" },
  { char: "🚗", label: "Oncoming automobile", category: "places" },
  { char: "🚘", label: "Sport utility vehicle", category: "places" },
  { char: "🚙", label: "Delivery truck", category: "places" },
  { char: "🚚", label: "Articulated lorry", category: "places" },
  { char: "🚛", label: "Tractor", category: "places" },
  { char: "🏎️", label: "Racing car", category: "places" },
  { char: "🏍️", label: "Motorcycle", category: "places" },
  { char: "🛵", label: "Motor scooter", category: "places" },
  { char: "🦽", label: "Manual wheelchair", category: "places" },
  { char: "🦼", label: "Motorized wheelchair", category: "places" },
  { char: "🛺", label: "Auto rickshaw", category: "places" },
  { char: "🚲", label: "Bicycle", category: "places" },
  { char: "🛴", label: "Kick scooter", category: "places" },
  { char: "🛹", label: "Skateboard", category: "places" },
  { char: "🛼", label: "Roller skate", category: "places" },
  { char: "🚏", label: "Bus stop", category: "places" },
  { char: "🛣️", label: "Motorway", category: "places" },
  { char: "🛤️", label: "Railway track", category: "places" },
  { char: "🛢️", label: "Oil drum", category: "places" },
  { char: "⛽", label: "Fuel pump", category: "places" },
  { char: "🚨", label: "Police car light", category: "places" },
  { char: "🚥", label: "Horizontal traffic light", category: "places" },
  { char: "🚦", label: "Vertical traffic light", category: "places" },
  { char: "🛑", label: "Stop sign", category: "places" },
  { char: "🚧", label: "Construction", category: "places" },
  { char: "⚓", label: "Anchor", category: "places" },
  { char: "⛵", label: "Sailboat", category: "places" },
  { char: "🛶", label: "Canoe", category: "places" },
  { char: "🚤", label: "Speedboat", category: "places" },
  { char: "🛳️", label: "Passenger ship", category: "places" },
  { char: "⛴️", label: "Ferry", category: "places" },
  { char: "🚢", label: "Ship", category: "places" },
  { char: "✈️", label: "Airplane", category: "places" },
  { char: "🛩️", label: "Small airplane", category: "places" },
  { char: "🛫", label: "Airplane departure", category: "places" },
  { char: "🛬", label: "Airplane arrival", category: "places" },
  { char: "🪂", label: "Parachute", category: "places" },
  { char: "💺", label: "Seat", category: "places" },
  { char: "🚁", label: "Helicopter", category: "places" },
  { char: "🚟", label: "Suspension railway", category: "places" },
  { char: "🚠", label: "Mountain cableway", category: "places" },
  { char: "🚡", label: "Aerial tramway", category: "places" },
  { char: "🛰️", label: "Satellite", category: "places" },
  { char: "🚀", label: "Rocket", category: "places" },
  { char: "🛸", label: "Flying saucer", category: "places" },
  { char: "🛎️", label: "Bellhop bell", category: "places" },
  { char: "🧳", label: "Luggage", category: "places" },
  { char: "⌛", label: "Hourglass done", category: "places" },
  { char: "⏳", label: "Hourglass not done", category: "places" },
  { char: "⌚", label: "Watch", category: "places" },
  { char: "⏰", label: "Alarm clock", category: "places" },
  { char: "⏱️", label: "Stopwatch", category: "places" },
  { char: "⏲️", label: "Timer clock", category: "places" },
  { char: "🕰️", label: "Mantelpiece clock", category: "places" },
  { char: "🕛", label: "Twelve o’clock", category: "places" },
  { char: "🕧", label: "Twelve-thirty", category: "places" },
  { char: "🕐", label: "One o’clock", category: "places" },
  { char: "🕜", label: "One-thirty", category: "places" },
  { char: "🕑", label: "Two o’clock", category: "places" },
  { char: "🕝", label: "Two-thirty", category: "places" },
  { char: "🕒", label: "Three o’clock", category: "places" },
  { char: "🕞", label: "Three-thirty", category: "places" },
  { char: "🕓", label: "Four o’clock", category: "places" },
  { char: "🕟", label: "Four-thirty", category: "places" },
  { char: "🕔", label: "Five o’clock", category: "places" },
  { char: "🕠", label: "Five-thirty", category: "places" },
  { char: "🕕", label: "Six o’clock", category: "places" },
  { char: "🕡", label: "Six-thirty", category: "places" },
  { char: "🕖", label: "Seven o’clock", category: "places" },
  { char: "🕢", label: "Seven-thirty", category: "places" },
  { char: "🕗", label: "Eight o’clock", category: "places" },
  { char: "🕣", label: "Eight-thirty", category: "places" },
  { char: "🕘", label: "Nine o’clock", category: "places" },
  { char: "🕤", label: "Nine-thirty", category: "places" },
  { char: "🕙", label: "Ten o’clock", category: "places" },
  { char: "🕥", label: "Ten-thirty", category: "places" },
  { char: "🕚", label: "Eleven o’clock", category: "places" },
  { char: "🕦", label: "Eleven-thirty", category: "places" },
  { char: "🌑", label: "New moon", category: "places" },
  { char: "🌒", label: "Waxing crescent moon", category: "places" },
  { char: "🌓", label: "First quarter moon", category: "places" },
  { char: "🌔", label: "Waxing gibbous moon", category: "places" },
  { char: "🌕", label: "Full moon", category: "places" },
  { char: "🌖", label: "Waning gibbous moon", category: "places" },
  { char: "🌗", label: "Last quarter moon", category: "places" },
  { char: "🌘", label: "Waning crescent moon", category: "places" },
  { char: "🌙", label: "Crescent moon", category: "places" },
  { char: "🌚", label: "New moon face", category: "places" },
  { char: "🌛", label: "First quarter moon face", category: "places" },
  { char: "🌜", label: "Last quarter moon face", category: "places" },
  { char: "🌡️", label: "Thermometer", category: "places" },
  { char: "☀️", label: "Sun", category: "places" },
  { char: "🌝", label: "Full moon face", category: "places" },
  { char: "🌞", label: "Sun with face", category: "places" },
  { char: "🪐", label: "Ringed planet", category: "places" },
  { char: "⭐", label: "Star", category: "places" },
  { char: "🌟", label: "Glowing star", category: "places" },
  { char: "🌠", label: "Shooting star", category: "places" },
  { char: "🌌", label: "Milky Way", category: "places" },
  { char: "☁️", label: "Cloud", category: "places" },
  { char: "⛅", label: "Sun behind cloud", category: "places" },
  { char: "⛈️", label: "Cloud with lightning and rain", category: "places" },
  { char: "🌤️", label: "Sun behind small cloud", category: "places" },
  { char: "🌥️", label: "Sun behind large cloud", category: "places" },
  { char: "🌦️", label: "Sun behind rain cloud", category: "places" },
  { char: "🌧️", label: "Cloud with rain", category: "places" },
  { char: "🌨️", label: "Cloud with snow", category: "places" },
  { char: "🌩️", label: "Cloud with lightning", category: "places" },
  { char: "🌪️", label: "Tornado", category: "places" },
  { char: "🌫️", label: "Fog", category: "places" },
  { char: "🌬️", label: "Wind face", category: "places" },
  { char: "🌀", label: "Cyclone", category: "places" },
  { char: "🌈", label: "Rainbow", category: "places" },
  { char: "🌂", label: "Closed umbrella", category: "places" },
  { char: "☂️", label: "Umbrella", category: "places" },
  { char: "☔", label: "Umbrella with rain drops", category: "places" },
  { char: "⛱️", label: "Beach with umbrella", category: "places" },
  { char: "⚡", label: "High voltage", category: "places" },
  { char: "❄️", label: "Snowflake", category: "places" },
  { char: "☃️", label: "Snowman", category: "places" },
  { char: "⛄", label: "Snowman without snow", category: "places" },
  { char: "☄️", label: "Comet", category: "places" },
  { char: "🔥", label: "Fire", category: "places" },
  { char: "💧", label: "Droplet", category: "places" },
  { char: "🌊", label: "Water wave", category: "places" },
];
