/**
 * Signal Share Emoji Pack
 * A comprehensive list of emojis for the Direct Messenger.
 */

export const EMOJI_PACK = [
  // Smilies & Emotion
  { char: "😀", label: "Grinning face" },
  { char: "😂", label: "Tears of joy" },
  { char: "😍", label: "Heart eyes" },
  { char: "🥰", label: "Smiling face with hearts" },
  { char: "😎", label: "Smiling face with sunglasses" },
  { char: "🥳", label: "Partying face" },
  { char: "🤩", label: "Star-struck" },
  { char: "😊", label: "Smiling face with smiling eyes" },
  { char: "😇", label: "Smiling face with halo" },
  { char: "🤔", label: "Thinking face" },
  { char: "🤨", label: "Face with raised eyebrow" },
  { char: "🤫", label: "Shushing face" },
  { char: "🤤", label: "Drooling face" },
  { char: "😴", label: "Sleeping face" },
  { char: "🤢", label: "Nauseated face" },
  { char: "🤯", label: "Exploding head" },
  { char: "😭", label: "Loudly crying face" },
  { char: "😤", label: "Face with steam from nose" },
  { char: "😡", label: "Pouting face" },
  { char: "🥺", label: "Pleading face" },
  { char: "✨", label: "Sparkles" },
  { char: "🔥", label: "Fire" },
  { char: "💯", label: "One hundred" },
  { char: "❤️", label: "Red heart" },
  { char: "🧡", label: "Orange heart" },
  { char: "💛", label: "Yellow heart" },
  { char: "💚", label: "Green heart" },
  { char: "💙", label: "Blue heart" },
  { char: "💜", label: "Purple heart" },
  { char: "🖤", label: "Black heart" },
  { char: "🤍", label: "White heart" },
  { char: "🤎", label: "Brown heart" },
  { char: "💔", label: "Broken heart" },
  { char: "❣️", label: "Heart exclamation" },
  { char: "💕", label: "Two hearts" },

  // Gestures & Body
  { char: "👍", label: "Thumbs up" },
  { char: "👎", label: "Thumbs down" },
  { char: "👌", label: "OK hand" },
  { char: "✌️", label: "Victory hand" },
  { char: "🤞", label: "Crossed fingers" },
  { char: "🤟", label: "Love-you gesture" },
  { char: "🤘", label: "Sign of the horns" },
  { char: "🤙", label: "Call me hand" },
  { char: "👊", label: "Oncoming fist" },
  { char: "👏", label: "Clapping hands" },
  { char: "🙌", label: "Raising hands" },
  { char: "👐", label: "Open hands" },
  { char: "🤲", label: "Palms up together" },
  { char: "🙏", label: "Folded hands" },
  { char: "🤝", label: "Handshake" },
  { char: "💪", label: "Flexed biceps" },
  { char: "🦾", label: "Mechanical arm" },
  { char: "🧠", label: "Brain" },
  { char: "👀", label: "Eyes" },

  // Objects & Symbols
  { char: "🎉", label: "Party popper" },
  { char: "🎊", label: "Confetti ball" },
  { char: "🎈", label: "Balloon" },
  { char: "🎁", label: "Wrapped gift" },
  { char: "💎", label: "Gem stone" },
  { char: "💡", label: "Light bulb" },
  { char: "🔋", label: "Battery" },
  { char: "💻", label: "Laptop" },
  { char: "📱", label: "Mobile phone" },
  { char: "🚀", label: "Rocket" },
  { char: "🛸", label: "Flying saucer" },
  { char: "🌈", label: "Rainbow" },
  { char: "🌊", label: "Water wave" },
  { char: "🌍", label: "Earth globe Europe-Africa" },
  { char: "🍕", label: "Pizza" },
  { char: "🍔", label: "Hamburger" },
  { char: "🍟", label: "French fries" },
  { char: "☕", label: "Hot beverage" },
  { char: "🍺", label: "Beer mug" },
  { char: "🍷", label: "Wine glass" },
  { char: "🍹", label: "Tropical drink" },
  { char: "🍦", label: "Soft ice cream" },
  { char: "🍩", label: "Doughnut" },
  { char: "🍪", label: "Cookie" },
  { char: "🍫", label: "Chocolate bar" },
];
