export default [
  { char: "😀", label: "Grinning face", category: "faces", tags: "happy joy smile" },
  { char: "😂", label: "Tears of joy", category: "faces", tags: "laugh lol happy joy" },
  { char: "😍", label: "Heart eyes", category: "faces", tags: "love adore like heart" },
  { char: "🥰", label: "Smiling face with hearts", category: "faces", tags: "love affection crush" },
  { char: "😎", label: "Smiling face with sunglasses", category: "faces", tags: "cool chill sun" },
  { char: "🥳", label: "Partying face", category: "faces", tags: "party celebration birthday" },
  { char: "🤩", label: "Star-struck", category: "faces", tags: "star wow amazed" },
  { char: "😊", label: "Smiling face with smiling eyes", category: "faces", tags: "happy shy smile" },
  { char: "😇", label: "Smiling face with halo", category: "faces", tags: "angel good innocent" },
  { char: "🤔", label: "Thinking face", category: "faces", tags: "think puzzle question" },
  { char: "🤨", label: "Face with raised eyebrow", category: "faces", tags: "skeptical doubt hmmm" },
  { char: "🤫", label: "Shushing face", category: "faces", tags: "quiet silence secret" },
  { char: "🤤", label: "Drooling face", category: "faces", tags: "hungry delicious want" },
  { char: "😴", label: "Sleeping face", category: "faces", tags: "sleep tired zzz" },
  { char: "🤢", label: "Nauseated face", category: "faces", tags: "sick gross vomit" },
  { char: "🤯", label: "Exploding head", category: "faces", tags: "mind blown shock wow" },
  { char: "😭", label: "Loudly crying face", category: "faces", tags: "sad cry upset" },
  { char: "😤", label: "Face with steam from nose", category: "faces" },
  { char: "😡", label: "Pouting face", category: "faces" },
  { char: "🥺", label: "Pleading face", category: "faces" },
  { char: "✨", label: "Sparkles", category: "faces" },
  { char: "🔥", label: "Fire", category: "faces" },
  { char: "💯", label: "One hundred", category: "faces" },
  { char: "❤️", label: "Red heart", category: "faces" },
  { char: "🧡", label: "Orange heart", category: "faces" },
  { char: "💛", label: "Yellow heart", category: "faces" },
  { char: "💚", label: "Green heart", category: "faces" },
  { char: "💙", label: "Blue heart", category: "faces" },
  { char: "💜", label: "Purple heart", category: "faces" },
  { char: "🖤", label: "Black heart", category: "faces" },
  { char: "🤍", label: "White heart", category: "faces" },
  { char: "🤎", label: "Brown heart", category: "faces" },
  { char: "💔", label: "Broken heart", category: "faces" },
  { char: "❣️", label: "Heart exclamation", category: "faces" },
  { char: "💕", label: "Two hearts", category: "faces" },
  { char: "🤪", label: "Zany face", category: "faces" },
  { char: "🫠", label: "Melting face", category: "faces" },
  { char: "🫡", label: "Saluting face", category: "faces" },
  { char: "🫢", label: "Face with open eyes and hand over mouth", category: "faces" },
  { char: "🫣", label: "Face with peeking eye", category: "faces" },
  { char: "🥱", label: "Yawning face", category: "faces", tags: "tired sleepy bored" },
  { char: "🤡", label: "Clown face", category: "faces", tags: "clown funny circus" },
  { char: "💀", label: "Skull", category: "faces", tags: "dead death bone ghost" },
  { char: "👽", label: "Alien", category: "faces", tags: "alien space ufo" },
  { char: "👾", label: "Alien monster", category: "faces", tags: "alien game monster" },
  { char: "🤖", label: "Robot", category: "faces", tags: "robot bot tech" },
  { char: "🎃", label: "Jack-o-lantern", category: "faces", tags: "halloween pumpkin scary" },
  { char: "👻", label: "Ghost", category: "faces", tags: "ghost scary halloween" },
  { char: "💩", label: "Pile of poo", category: "faces", tags: "poop shit smile" },
  { char: "👿", label: "Angry face with horns", category: "faces", tags: "devil evil angry" },
  { char: "👹", label: "Ogre", category: "faces", tags: "monster scary ogre" },
  { char: "👺", label: "Goblin", category: "faces", tags: "monster scary goblin" },
  { char: "😺", label: "Grinning cat", category: "faces", tags: "cat kitty animal" },
  { char: "😸", label: "Grinning cat with smiling eyes", category: "faces", tags: "cat kitty happy" },
  { char: "😻", label: "Smiling cat with heart-eyes", category: "faces", tags: "cat love heart" },
  { char: "😽", label: "Kissing cat", category: "faces", tags: "cat kiss love" },
  { char: "🙀", label: "Weary cat", category: "faces", tags: "cat shock wow" },
  { char: "😿", label: "Crying cat", category: "faces", tags: "cat sad cry" },
  { char: "😾", label: "Pouting cat", category: "faces", tags: "cat angry mad" },
  { char: "🙈", label: "See-no-evil monkey", category: "faces", tags: "monkey hide see" },
  { char: "🙉", label: "Hear-no-evil monkey", category: "faces", tags: "monkey hide hear" },
  { char: "🙊", label: "Speak-no-evil monkey", category: "faces", tags: "monkey hide speak" },
  { char: "💋", label: "Kiss mark", category: "faces", tags: "kiss love lips" },
  { char: "💌", label: "Love letter", category: "faces", tags: "love letter mail" },
  { char: "💘", label: "Heart with arrow", category: "faces", tags: "love heart cupid" },
  { char: "💝", label: "Heart with ribbon", category: "faces", tags: "love heart gift" },
  { char: "💖", label: "Sparkling heart", category: "faces", tags: "love heart sparkle" },
  { char: "💗", label: "Growing heart", category: "faces", tags: "love heart grow" },
  { char: "💓", label: "Beating heart", category: "faces", tags: "love heart beat" },
  { char: "💞", label: "Revolving hearts", category: "faces", tags: "love heart spin" },
  { char: "💟", label: "Heart decoration", category: "faces", tags: "love heart deco" },
  { char: "💢", label: "Anger symbol", category: "faces", tags: "angry mad anime" },
  { char: "💥", label: "Collision", category: "faces" },
  { char: "💫", label: "Dizzy", category: "faces" },
  { char: "💦", label: "Sweat droplets", category: "faces" },
  { char: "💨", label: "Dash", category: "faces" },
  { char: "💬", label: "Speech balloon", category: "faces" },
  { char: "💭", label: "Thought balloon", category: "faces" },
  { char: "💤", label: "Zzz", category: "faces" }
];
