export default [
  { char: "🍇", label: "Grapes", category: "food" },
  { char: "🍈", label: "Melon", category: "food" },
  { char: "🍉", label: "Watermelon", category: "food" },
  { char: "🍊", label: "Tangerine", category: "food" },
  { char: "🍋", label: "Lemon", category: "food" },
  { char: "🍌", label: "Banana", category: "food" },
  { char: "🍍", label: "Pineapple", category: "food" },
  { char: "🥭", label: "Mango", category: "food" },
  { char: "🍎", label: "Red apple", category: "food", tags: "apple fruit red" },
  { char: "🍏", label: "Green apple", category: "food", tags: "apple fruit green" },
  { char: "🍐", label: "Pear", category: "food", tags: "pear fruit" },
  { char: "🍑", label: "Peach", category: "food" },
  { char: "🍒", label: "Cherries", category: "food" },
  { char: "🍓", label: "Strawberry", category: "food" },
  { char: "🥝", label: "Kiwi fruit", category: "food" },
  { char: "🍅", label: "Tomato", category: "food" },
  { char: "🥥", label: "Coconut", category: "food" },
  { char: "🥑", label: "Avocado", category: "food" },
  { char: "🍆", label: "Eggplant", category: "food" },
  { char: "🥔", label: "Potato", category: "food" },
  { char: "🥕", label: "Carrot", category: "food" },
  { char: "🌽", label: "Ear of corn", category: "food" },
  { char: "🌶️", label: "Hot pepper", category: "food" },
  { char: "🥒", label: "Cucumber", category: "food" },
  { char: "🥬", label: "Leafy green", category: "food" },
  { char: "🥦", label: "Broccoli", category: "food" },
  { char: "🧄", label: "Garlic", category: "food" },
  { char: "🧅", label: "Onion", category: "food" },
  { char: "🍄", label: "Mushroom", category: "food" },
  { char: "🥜", label: "Peanuts", category: "food" },
  { char: "🌰", label: "Chestnut", category: "food" },
  { char: "🍞", label: "Bread", category: "food" },
  { char: "🥐", label: "Croissant", category: "food" },
  { char: "🥖", label: "Baguette bread", category: "food" },
  { char: "🥨", label: "Pretzel", category: "food" },
  { char: "🥯", label: "Bagel", category: "food" },
  { char: "🥞", label: "Pancakes", category: "food" },
  { char: "🧇", label: "Waffle", category: "food" },
  { char: "🧀", label: "Cheese wedge", category: "food" },
  { char: "🍖", label: "Meat on bone", category: "food" },
  { char: "🍗", label: "Poultry leg", category: "food" },
  { char: "🥩", label: "Cut of meat", category: "food" },
  { char: "🥓", label: "Bacon", category: "food" },
  { char: "🍔", label: "Hamburger", category: "food" },
  { char: "🍟", label: "French fries", category: "food" },
  { char: "🍕", label: "Pizza", category: "food" },
  { char: "🌭", label: "Hot dog", category: "food" },
  { char: "🥪", label: "Sandwich", category: "food" },
  { char: "🌮", label: "Taco", category: "food" },
  { char: "🌯", label: "Burrito", category: "food" },
  { char: "🥙", label: "Stuffed flatbread", category: "food" },
  { char: "🧆", label: "Falafel", category: "food" },
  { char: "🥚", label: "Egg", category: "food", tags: "egg breakfast" },
  { char: "🍳", label: "Cooking", category: "food" },
  { char: "🥘", label: "Shallow pan of food", category: "food" },
  { char: "🍲", label: "Pot of food", category: "food" },
  { char: "🥣", label: "Bowl with spoon", category: "food" },
  { char: "🥗", label: "Green salad", category: "food" },
  { char: "🍿", label: "Popcorn", category: "food" },
  { char: "🧈", label: "Butter", category: "food" },
  { char: "🧂", label: "Salt", category: "food" },
  { char: "🥫", label: "Canned food", category: "food" },
  { char: "🍱", label: "Bento box", category: "food" },
  { char: "🍘", label: "Rice cracker", category: "food" },
  { char: "🍙", label: "Rice ball", category: "food" },
  { char: "🍚", label: "Cooked rice", category: "food" },
  { char: "🍛", label: "Curry rice", category: "food" },
  { char: "🍜", label: "Steaming bowl", category: "food" },
  { char: "🍝", label: "Spaghetti", category: "food" },
  { char: "🍠", label: "Roasted sweet potato", category: "food" },
  { char: "🍢", label: "Oden", category: "food" },
  { char: "🍣", label: "Sushi", category: "food" },
  { char: "🍤", label: "Fried shrimp", category: "food" },
  { char: "🍥", label: "Fish cake with swirl", category: "food" },
  { char: "🥮", label: "Moon cake", category: "food" },
  { char: "🍡", label: "Dango", category: "food" },
  { char: "🥟", label: "Dumpling", category: "food" },
  { char: "🥠", label: "Fortune cookie", category: "food" },
  { char: "🥡", label: "Takeout box", category: "food" },
  { char: "🦀", label: "Crab", category: "food", tags: "crab sea food" },
  { char: "🦞", label: "Lobster", category: "food", tags: "lobster sea food" },
  { char: "🦐", label: "Shrimp", category: "food", tags: "shrimp sea food" },
  { char: "🦑", label: "Squid", category: "food", tags: "squid sea food" },
  { char: "🦪", label: "Oyster", category: "food", tags: "oyster sea food" },
  { char: "🍦", label: "Soft ice cream", category: "food" },
  { char: "🍧", label: "Shaved ice", category: "food" },
  { char: "🍨", label: "Ice cream", category: "food" },
  { char: "🍩", label: "Doughnut", category: "food" },
  { char: "🍪", label: "Cookie", category: "food" },
  { char: "🎂", label: "Birthday cake", category: "food" },
  { char: "🍰", label: "Shortcake", category: "food" },
  { char: "🧁", label: "Cupcake", category: "food" },
  { char: "🥧", label: "Pie", category: "food" },
  { char: "🍫", label: "Chocolate bar", category: "food" },
  { char: "🍬", label: "Candy", category: "food" },
  { char: "🍭", label: "Lollipop", category: "food" },
  { char: "🍮", label: "Custard", category: "food" },
  { char: "🍯", label: "Honey pot", category: "food" },
  { char: "🍼", label: "Baby bottle", category: "food" },
  { char: "🥛", label: "Glass of milk", category: "food" },
  { char: "☕", label: "Hot beverage", category: "food" },
  { char: "🍵", label: "Teacup without handle", category: "food" },
  { char: "🍶", label: "Sake", category: "food" },
  { char: "🍾", label: "Bottle with popping cork", category: "food" },
  { char: "🍷", label: "Wine glass", category: "food" },
  { char: "🍸", label: "Cocktail glass", category: "food" },
  { char: "🍹", label: "Tropical drink", category: "food" },
  { char: "🍺", label: "Beer mug", category: "food" },
  { char: "🍻", label: "Clinking beer mugs", category: "food" },
  { char: "🥂", label: "Clinking glasses", category: "food" },
  { char: "🥃", label: "Tumbler glass", category: "food" },
  { char: "🥤", label: "Cup with straw", category: "food" },
  { char: "🧃", label: "Beverage box", category: "food" },
  { char: "🧉", label: "Mate", category: "food" },
  { char: "🧊", label: "Ice", category: "food" },
  { char: "🥢", label: "Chopsticks", category: "food" },
  { char: "🍽️", label: "Fork and knife with plate", category: "food" },
  { char: "🍴", label: "Fork and knife", category: "food" },
  { char: "🥄", label: "Spoon", category: "food" }
];
