export default [
  { char: "👍", label: "Thumbs up", category: "gestures", tags: "yes good okay like" },
  { char: "👎", label: "Thumbs down", category: "gestures", tags: "no bad dislike" },
  { char: "👌", label: "OK hand", category: "gestures", tags: "ok okay good" },
  { char: "✌️", label: "Victory hand", category: "gestures", tags: "peace victory two" },
  { char: "🤞", label: "Crossed fingers", category: "gestures", tags: "luck hope" },
  { char: "🤟", label: "Love-you gesture", category: "gestures" },
  { char: "🤘", label: "Sign of the horns", category: "gestures", tags: "rock metal music" },
  { char: "🤙", label: "Call me hand", category: "gestures", tags: "call phone shaka" },
  { char: "👊", label: "Oncoming fist", category: "gestures" },
  { char: "👏", label: "Clapping hands", category: "gestures", tags: "clap bravo well done" },
  { char: "🙌", label: "Raising hands", category: "gestures", tags: "praise celebrate joy" },
  { char: "👐", label: "Open hands", category: "gestures" },
  { char: "🤲", label: "Palms up together", category: "gestures" },
  { char: "🙏", label: "Folded hands", category: "gestures", tags: "pray please thanks" },
  { char: "🤝", label: "Handshake", category: "gestures", tags: "deal agree meet" },
  { char: "💪", label: "Flexed biceps", category: "gestures", tags: "strong muscle power" },
  { char: "🦾", label: "Mechanical arm", category: "gestures" },
  { char: "🧠", label: "Brain", category: "gestures", tags: "brain smart think" },
  { char: "👀", label: "Eyes", category: "gestures" },
  { char: "🖕", label: "Middle finger", category: "gestures" },
  { char: "💅", label: "Nail polish", category: "gestures" },
  { char: "🤳", label: "Selfie", category: "gestures" },
  { char: "🦶", label: "Foot", category: "gestures" },
  { char: "🦵", label: "Leg", category: "gestures" },
  { char: "🦿", label: "Mechanical leg", category: "gestures" },
  { char: "✍️", label: "Writing hand", category: "gestures" },
  { char: "🫂", label: "People hugging", category: "gestures" },
  { char: "👂", label: "Ear", category: "gestures" },
  { char: "👃", label: "Nose", category: "gestures" },
  { char: "👅", label: "Tongue", category: "gestures" },
  { char: "👄", label: "Mouth", category: "gestures" }
];
