export default [
  { char: "🌿", label: "Herb", category: "nature" },
  { char: "🌵", label: "Cactus", category: "nature" },
  { char: "🌴", label: "Palm tree", category: "nature" },
  { char: "🌲", label: "Evergreen tree", category: "nature" },
  { char: "🌳", label: "Deciduous tree", category: "nature" },
  { char: "☘️", label: "Shamrock", category: "nature" },
  { char: "🍀", label: "Four leaf clover", category: "nature" },
  { char: "🍁", label: "Maple leaf", category: "nature" },
  { char: "🍂", label: "Fallen leaf", category: "nature" },
  { char: "🍄", label: "Mushroom", category: "nature" },
  { char: "🌹", label: "Rose", category: "nature" },
  { char: "🌺", label: "Hibiscus", category: "nature" },
  { char: "🌻", label: "Sunflower", category: "nature" },
  { char: "🌼", label: "Blossom", category: "nature" },
  { char: "🌷", label: "Tulip", category: "nature" },
  { char: "🪐", label: "Ringed planet", category: "nature" },
  { char: "🌙", label: "Crescent moon", category: "nature" },
  { char: "⭐", label: "Star", category: "nature" },
  { char: "☀️", label: "Sun", category: "nature" },
  { char: "☁️", label: "Cloud", category: "nature" },
  { char: "❄️", label: "Snowflake", category: "nature" },
  { char: "⚡", label: "Voltage", category: "nature" },
  { char: "🔥", label: "Fire", category: "nature" }
];
