export default [
  { char: "🌍", label: "Earth globe Europe-Africa", category: "places" },
  { char: "🌎", label: "Earth globe Americas", category: "places" },
  { char: "🌏", label: "Earth globe Asia-Australia", category: "places" },
  { char: "🌐", label: "Globe with meridians", category: "places" },
  { char: "🗺️", label: "World map", category: "places" },
  { char: "🗾", label: "Map of Japan", category: "places" },
  { char: "🧭", label: "Compass", category: "places" },
  { char: "🏔️", label: "Snow-capped mountain", category: "places" },
  { char: "⛰️", label: "Mountain", category: "places" },
  { char: "🌋", label: "Volcano", category: "places" },
  { char: "🗻", label: "Mount Fuji", category: "places" },
  { char: "🏕️", label: "Camping", category: "places" },
  { char: "🏖️", label: "Beach with umbrella", category: "places" },
  { char: "🏜️", label: "Desert", category: "places" },
  { char: "🏝️", label: "Desert island", category: "places" },
  { char: "🏝️", label: "National park", category: "places" },
  { char: "🏞️", label: "Stadium", category: "places" },
  { char: "🏟️", label: "Classical building", category: "places" },
  { char: "🏛️", label: "Building construction", category: "places" },
  { char: "🏗️", label: "Brick", category: "places" },
  { char: "🧱", label: "Houses", category: "places" },
  { char: "🏘️", label: "Derelict house", category: "places" },
  { char: "🏚️", label: "House", category: "places" },
  { char: "🏠", label: "House with garden", category: "places" },
  { char: "🏡", label: "Office building", category: "places" },
  { char: "🏢", label: "Japanese post office", category: "places" },
  { char: "🏣", label: "Post office", category: "places" },
  { char: "🏤", label: "Hospital", category: "places" },
  { char: "🏥", label: "Bank", category: "places" },
  { char: "🏦", label: "Hotel", category: "places" },
  { char: "🏨", label: "Love hotel", category: "places" },
  { char: "🏩", label: "Convenience store", category: "places" },
  { char: "🏪", label: "School", category: "places" },
  { char: "🏫", label: "Department store", category: "places" },
  { char: "🏬", label: "Factory", category: "places" },
  { char: "🏭", label: "Japanese castle", category: "places" },
  { char: "🏯", label: "Castle", category: "places" },
  { char: "🏰", label: "Wedding", category: "places" },
  { char: "💒", label: "Tokyo tower", category: "places" },
  { char: "🗼", label: "Statue of Liberty", category: "places" },
  { char: "🗽", label: "Church", category: "places" },
  { char: "⛪", label: "Mosque", category: "places" },
  { char: "🕌", label: "Hindu temple", category: "places" },
  { char: "🛕", label: "Synagogue", category: "places" },
  { char: "🕍", label: "Shinto shrine", category: "places" },
  { char: "⛩️", label: "Kaaba", category: "places" },
  { char: "🕋", label: "Fountain", category: "places" },
  { char: "⛲", label: "Tent", category: "places" },
  { char: "⛺", label: "Foggy", category: "places" },
  { char: "🌁", label: "Night with stars", category: "places" },
  { char: "🌃", label: "Cityscape", category: "places" },
  { char: "🏙️", label: "Sunrise over mountains", category: "places" },
  { char: "🌄", label: "Sunrise", category: "places" },
  { char: "🌅", label: "Cityscape at dusk", category: "places" },
  { char: "🌆", label: "Sunset", category: "places" },
  { char: "🌇", label: "Bridge at night", category: "places" },
  { char: "🌉", label: "Hot springs", category: "places" },
  { char: "♨️", label: "Carousel horse", category: "places" },
  { char: "🎠", label: "Ferris wheel", category: "places" },
  { char: "🎡", label: "Roller coaster", category: "places" },
  { char: "🎢", label: "Barber pole", category: "places" },
  { char: "💈", label: "Circus tent", category: "places" },
  { char: "🎪", label: "Locomotive", category: "places" },
  { char: "🚂", label: "Railway car", category: "places" },
  { char: "🚃", label: "High-speed train", category: "places" },
  { char: "🚄", label: "Bullet train", category: "places" },
  { char: "🚅", label: "Train", category: "places" },
  { char: "🚆", label: "Metro", category: "places" },
  { char: "🚇", label: "Light rail", category: "places" },
  { char: "🚈", label: "Station", category: "places" },
  { char: "🚉", label: "Tram", category: "places" },
  { char: "🚊", label: "Monorail", category: "places" },
  { char: "🚝", label: "Mountain railway", category: "places" },
  { char: "🚞", label: "Tram car", category: "places" },
  { char: "🚋", label: "Bus", category: "places" },
  { char: "🚌", label: "Oncoming bus", category: "places" },
  { char: "🚍", label: "Trolleybus", category: "places" },
  { char: "🚎", label: "Minibus", category: "places" },
  { char: "🚐", label: "Ambulance", category: "places" },
  { char: "🚑", label: "Fire engine", category: "places" },
  { char: "🚒", label: "Police car", category: "places" },
  { char: "🚓", label: "Oncoming police car", category: "places" },
  { char: "🚔", label: "Taxi", category: "places" },
  { char: "🚕", label: "Oncoming taxi", category: "places" },
  { char: "🚖", label: "Automobile", category: "places" },
  { char: "🚗", label: "Oncoming automobile", category: "places" },
  { char: "🚘", label: "Sport utility vehicle", category: "places" },
  { char: "🚙", label: "Delivery truck", category: "places" },
  { char: "🚚", label: "Articulated lorry", category: "places" },
  { char: "🚛", label: "Tractor", category: "places" },
  { char: "🏎️", label: "Racing car", category: "places" },
  { char: "🏍️", label: "Motorcycle", category: "places" },
  { char: "🛵", label: "Motor scooter", category: "places" },
  { char: "🦽", label: "Manual wheelchair", category: "places" },
  { char: "🦼", label: "Motorized wheelchair", category: "places" },
  { char: "🛺", label: "Auto rickshaw", category: "places" },
  { char: "🚲", label: "Bicycle", category: "places" },
  { char: "🛴", label: "Kick scooter", category: "places" },
  { char: "🛹", label: "Skateboard", category: "places" },
  { char: "🛼", label: "Roller skate", category: "places" },
  { char: "🚏", label: "Bus stop", category: "places" },
  { char: "🛣️", label: "Motorway", category: "places" },
  { char: "🛤️", label: "Railway track", category: "places" },
  { char: "🛢️", label: "Oil drum", category: "places" },
  { char: "⛽", label: "Fuel pump", category: "places" },
  { char: "🚨", label: "Police car light", category: "places" },
  { char: "🚥", label: "Horizontal traffic light", category: "places" },
  { char: "🚦", label: "Vertical traffic light", category: "places" },
  { char: "🛑", label: "Stop sign", category: "places" },
  { char: "🚧", label: "Construction", category: "places" },
  { char: "⚓", label: "Anchor", category: "places" },
  { char: "⛵", label: "Sailboat", category: "places" },
  { char: "🛶", label: "Canoe", category: "places" },
  { char: "🚤", label: "Speedboat", category: "places" },
  { char: "🛳️", label: "Passenger ship", category: "places" },
  { char: "⛴️", label: "Ferry", category: "places" },
  { char: "🚢", label: "Ship", category: "places" },
  { char: "✈️", label: "Airplane", category: "places" },
  { char: "🛩️", label: "Small airplane", category: "places" },
  { char: "🛫", label: "Airplane departure", category: "places" },
  { char: "🛬", label: "Airplane arrival", category: "places" },
  { char: "🪂", label: "Parachute", category: "places" },
  { char: "💺", label: "Seat", category: "places" },
  { char: "🚁", label: "Helicopter", category: "places" },
  { char: "🚟", label: "Suspension railway", category: "places" },
  { char: "🚠", label: "Mountain cableway", category: "places" },
  { char: "🚡", label: "Aerial tramway", category: "places" },
  { char: "🛰️", label: "Satellite", category: "places" },
  { char: "🚀", label: "Rocket", category: "places" },
  { char: "🛸", label: "Flying saucer", category: "places" },
  { char: "🛎️", label: "Bellhop bell", category: "places" },
  { char: "🧳", label: "Luggage", category: "places" },
  { char: "⌛", label: "Hourglass done", category: "places" },
  { char: "⏳", label: "Hourglass not done", category: "places" },
  { char: "⌚", label: "Watch", category: "places" },
  { char: "⏰", label: "Alarm clock", category: "places" },
  { char: "⏱️", label: "Stopwatch", category: "places" },
  { char: "⏲️", label: "Timer clock", category: "places" },
  { char: "🕰️", label: "Mantelpiece clock", category: "places" },
  { char: "🕛", label: "Twelve o’clock", category: "places" },
  { char: "🕧", label: "Twelve-thirty", category: "places" },
  { char: "🕐", label: "One o’clock", category: "places" },
  { char: "🕜", label: "One-thirty", category: "places" },
  { char: "🕑", label: "Two o’clock", category: "places" },
  { char: "🕝", label: "Two-thirty", category: "places" },
  { char: "🕒", label: "Three o’clock", category: "places" },
  { char: "🕞", label: "Three-thirty", category: "places" },
  { char: "🕓", label: "Four o’clock", category: "places" },
  { char: "🕟", label: "Four-thirty", category: "places" },
  { char: "🕔", label: "Five o’clock", category: "places" },
  { char: "🕠", label: "Five-thirty", category: "places" },
  { char: "🕕", label: "Six o’clock", category: "places" },
  { char: "🕡", label: "Six-thirty", category: "places" },
  { char: "🕖", label: "Seven o’clock", category: "places" },
  { char: "🕢", label: "Seven-thirty", category: "places" },
  { char: "🕗", label: "Eight o’clock", category: "places" },
  { char: "🕣", label: "Eight-thirty", category: "places" },
  { char: "🕘", label: "Nine o’clock", category: "places" },
  { char: "🕤", label: "Nine-thirty", category: "places" },
  { char: "🕙", label: "Ten o’clock", category: "places" },
  { char: "🕥", label: "Ten-thirty", category: "places" },
  { char: "🕚", label: "Eleven o’clock", category: "places" },
  { char: "🕦", label: "Eleven-thirty", category: "places" },
  { char: "🌑", label: "New moon", category: "places" },
  { char: "🌒", label: "Waxing crescent moon", category: "places" },
  { char: "🌓", label: "First quarter moon", category: "places" },
  { char: "🌔", label: "Waxing gibbous moon", category: "places" },
  { char: "🌕", label: "Full moon", category: "places" },
  { char: "🌖", label: "Waning gibbous moon", category: "places" },
  { char: "🌗", label: "Last quarter moon", category: "places" },
  { char: "🌘", label: "Waning crescent moon", category: "places" },
  { char: "🌙", label: "Crescent moon", category: "places" },
  { char: "🌚", label: "New moon face", category: "places" },
  { char: "🌛", label: "First quarter moon face", category: "places" },
  { char: "🌜", label: "Last quarter moon face", category: "places" },
  { char: "🌡️", label: "Thermometer", category: "places" },
  { char: "☀️", label: "Sun", category: "places" },
  { char: "🌝", label: "Full moon face", category: "places" },
  { char: "🌞", label: "Sun with face", category: "places" },
  { char: "🪐", label: "Ringed planet", category: "places" },
  { char: "⭐", label: "Star", category: "places" },
  { char: "🌟", label: "Glowing star", category: "places" },
  { char: "🌠", label: "Shooting star", category: "places" },
  { char: "🌌", label: "Milky Way", category: "places" },
  { char: "☁️", label: "Cloud", category: "places" },
  { char: "⛅", label: "Sun behind cloud", category: "places" },
  { char: "⛈️", label: "Cloud with lightning and rain", category: "places" },
  { char: "🌤️", label: "Sun behind small cloud", category: "places" },
  { char: "🌥️", label: "Sun behind large cloud", category: "places" },
  { char: "🌦️", label: "Sun behind rain cloud", category: "places" },
  { char: "🌧️", label: "Cloud with rain", category: "places" },
  { char: "🌨️", label: "Cloud with snow", category: "places" },
  { char: "🌩️", label: "Cloud with lightning", category: "places" },
  { char: "🌪️", label: "Tornado", category: "places" },
  { char: "🌫️", label: "Fog", category: "places" },
  { char: "🌬️", label: "Wind face", category: "places" },
  { char: "🌀", label: "Cyclone", category: "places" },
  { char: "🌈", label: "Rainbow", category: "places" },
  { char: "🌂", label: "Closed umbrella", category: "places" },
  { char: "☂️", label: "Umbrella", category: "places" },
  { char: "☔", label: "Umbrella with rain drops", category: "places" },
  { char: "⛱️", label: "Beach with umbrella", category: "places" },
  { char: "⚡", label: "High voltage", category: "places" },
  { char: "❄️", label: "Snowflake", category: "places" },
  { char: "☃️", label: "Snowman", category: "places" },
  { char: "⛄", label: "Snowman without snow", category: "places" },
  { char: "☄️", label: "Comet", category: "places" },
  { char: "🔥", label: "Fire", category: "places" },
  { char: "💧", label: "Droplet", category: "places" },
  { char: "🌊", label: "Water wave", category: "places" }
];
