/**
 * /publish Command
 * Handles Workshop Arcade publish actions from the Arcade chat.
 * If called without arguments, it triggers a random game generation.
 */
(function() {
    function showPublishFeedback(message, isError = false) {
        if (!message) return;
        if (typeof window.showFeedback === "function") {
            window.showFeedback(message, isError);
            return;
        }
        if (typeof window.addChatMessage === "function") {
            window.addChatMessage("ai", isError ? `⚠️ ${message}` : message);
        }
    }

    window.ArcadeCommandManager.register({
        id: "publish",
        description: "Publish a random game or trigger AI generation.",

        execute: async (args, inputElement) => {
            const trimmedArgs = `${args || ""}`.trim();

            // If called without arguments, trigger a random game generation
            if (trimmedArgs.length === 0) {
                showPublishFeedback("Generating a random game idea...");
                
                // Use a timeout to allow the command manager to finish clearing the input,
                // then inject the random prompt and simulate Enter key.
                setTimeout(() => {
                    if (inputElement) {
                        const randomIdeas = [
                            "a random creative mini-game with a unique theme",
                            "a game like asteroids but with a twist",
                            "a paper-sketch style platformer game",
                            "a neon-themed puzzle game",
                            "a lo-fi pixel art farming game"
                        ];
                        const randomPrompt = randomIdeas[Math.floor(Math.random() * randomIdeas.length)];
                        
                        inputElement.value = `/publish ${randomPrompt}`;
                        const event = new KeyboardEvent('keydown', { key: 'Enter', bubbles: true });
                        inputElement.dispatchEvent(event);
                    }
                }, 100);
                
                return true; // Handled locally by re-submitting with a prompt
            }

            // If called with arguments, let the AI handle it
            window.activeArcadeCommandMode = "/publish";
            if (Array.isArray(window.activeArcadeCommandModes)) {
                if (!window.activeArcadeCommandModes.includes("/publish")) {
                    window.activeArcadeCommandModes.push("/publish");
                }
            } else {
                window.activeArcadeCommandModes = ["/publish"];
            }

            return false; // Let the AI generate the response
        },

        handleResponse: async (text, options = {}) => {
            const actionResult = {
                handled: false,
                workshopPublishAttempted: false,
                workshopPublishSucceeded: false,
                errorReason: null
            };

            const modes = new Set(Array.isArray(window.activeArcadeCommandModes) ? window.activeArcadeCommandModes : []);
            if (window.activeArcadeCommandMode) modes.add(window.activeArcadeCommandMode);

            if (!modes.has("/publish") && !text.includes('[PUBLISH]')) {
                return actionResult;
            }

            actionResult.handled = true;
            actionResult.workshopPublishAttempted = true;

            if (typeof window.publishCustomGameFromAi !== "function") {
                const feedbackMsg = "Workshop publishing is unavailable in this environment.";
                showPublishFeedback(feedbackMsg, true);
                actionResult.errorReason = feedbackMsg;
                return actionResult;
            }

            // Extract files from markdown code blocks
            const workshopFiles = [];
            const codeBlockRegex = /```(\w+)(?:\s+filename=([^\s]+))?\s*([\s\S]*?)```/g;
            let match;
            
            while ((match = codeBlockRegex.exec(text)) !== null) {
                const lang = match[1];
                const filename = match[2] || (workshopFiles.length === 0 ? "index.html" : `file_${workshopFiles.length}.${lang}`);
                let content = match[3].trim();
                
                // Sanitize JS files: remove leading/trailing HTML tags if generated by mistake
                if (filename.endsWith('.js') || lang === 'javascript' || lang === 'js') {
                    content = content.replace(/^<script[^>]*>/i, '').replace(/<\/script>$/i, '').trim();
                }
                
                workshopFiles.push({
                    name: filename,
                    type: lang,
                    content: content
                });
            }

            // Fallback: If no code blocks found, use the whole response as index.html
            if (workshopFiles.length === 0) {
                workshopFiles.push({
                    name: "index.html",
                    type: "html",
                    content: text.trim()
                });
            }

            // Extract title from prompt or use default
            const userPrompt = options.userPrompt || "";
            const titleMatch = userPrompt.match(/publish\s+(?:a\s+)?(?:new\s+)?(?:game\s+)?(?:called\s+)?["']([^"']+)["']/i) 
                || userPrompt.match(/publish\s+([^ ]+)/i);
            
            const title = titleMatch ? titleMatch[1] : "AI Generated Game";

            const publishPayload = {
                title: title,
                category: "GAME",
                description: `Published via /publish command.\nPrompt: ${userPrompt}`,
                thumbnail: "",
                tags: "arcade, ai",
                files: workshopFiles,
                mode: "create",
                gameId: "",
                updateTitle: ""
            };

            try {
                const workshopResult = await window.publishCustomGameFromAi(publishPayload);

                if (workshopResult?.ok) {
                    actionResult.workshopPublishSucceeded = true;
                    showPublishFeedback(`Published "${workshopResult.title}" in Workshop!`);
                    
                    if (typeof window.setWorkshopEditActiveGame === "function" && workshopResult.id) {
                        setTimeout(() => {
                            window.setWorkshopEditActiveGame(workshopResult.id);
                        }, 1000);
                    }
                } else {
                    const apiError = workshopResult?.message || "Failed to publish game to Workshop.";
                    actionResult.errorReason = apiError;
                    showPublishFeedback(apiError, true);
                }
            } catch (error) {
                console.error("[Arcade: Publish] Critical system failure:", error);
                actionResult.errorReason = error?.message || "Critical upload error.";
                showPublishFeedback(actionResult.errorReason, true);
            }

            window.activeArcadeCommandMode = null;
            window.activeArcadeCommandModes = [];
            
            return actionResult;
        }
    });
})();